version: "2"
run:
  issues-exit-code: 1
linters:
  enable:
    - copyloopvar
    - dupl
    - errname
    - forbidigo
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - lll
    - mirror
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - unparam
    - usestdlibvars
  settings:
    errcheck:
      check-type-assertions: true
    gocyclo:
      min-complexity: 10
    lll:
      line-length: 120
    prealloc:
      simple: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
